[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
dimensions = { columns = 134, lines = 36}
opacity = 0.8
blur = true

[font]
normal = {family = "CaskaydiaCove Nerd Font", style = "Regular"}
bold = {family = "CaskaydiaCove Nerd Font", style = "Bold"}
italic = {family = "CaskaydiaCove Nerd Font", style = "Italic"}
size = 12.0

[cursor]
style = {shape = "Beam", blinking = "On"}
thickness = 0.10

[keyboard]
bindings = [
{key = "C", mods = "Control", action = "Copy"},
{key = "V", mods = "Control", action = "Paste"},
{key = "C", mods = "Control", chars = "\u0003"},
]

[terminal]
shell = {program = "/usr/bin/zsh", args = ['-l', '-c', 'zellij']}
